### ISSUE TITLE
Should be able to close active step

### ISSUE THREAD

**Issue by joebochill** [pxblue/dynamic-stepper#2]
#### Bug or feature request?
Feature Request

#### What is the expected behavior?
You should be able to close the active step if it has a value selected (clicking the header should collapse the step)

#### What is the current behavior?
Clicking the header of the open step does nothing

#### What is your environment?

 Framework
- [x] Angular
- [ ] React

**Comment by daileytj** [comment]
Closing as this bug has been migrated to the angular-design-pattern monorepo. https://github.com/pxblue/angular-design-patterns/issues/32
