### ISSUE TITLE
Need Unit tests for removing items

### ISSUE THREAD

**Issue by joebochill** [pxblue/dynamic-stepper#5]
#### Bug or feature request?
Feature

#### What is the expected behavior?
There should be a unit test for the remove step functions

#### What is the current behavior?
No unit tests for removing

#### What is your environment?

 Framework
- [x] Angular
- [ ] React

**Comment by joebochill** [comment]
This is likely related to why we have the setTimeout in the app.component.ts file. If you add a setTimeout to the line that updates the activeIndex, the test succeeds as expected. Will need further exploration to understand what's going on.

**Comment by daileytj** [comment]
Closing as this bug was migrated to the angular-design-pattern monorepo. https://github.com/pxblue/angular-design-patterns/issues/31
